# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Naturschutz Richterswil-Samstagern
email: ratnaweera@naturschutz-r-s.ch
phone: 079 220 53 21
description: > # this means to ignore newlines until "baseurl:"
  Momentan setzen wir uns ganz praktisch für die Natur ein. Wir pflegen unser Vereinsbiotop, zahlreiche Nistkästen, pflanzen nach Bedarf Hecken und wir sind politisch aktiv in der Kommission Landwirtschaft, Forst und Naturschutz.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://naturschutz-richterswil-samstagern.github.io" # the base hostname & protocol for your site
twitter_username: sinndrin
github_username: rschaerer

# Build settings
markdown: kramdown

# How to handle permalinks in the front matter
relative_permalinks: false

# Reading Files
include:
  - _pages