# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Naturschutz Richterswil-Samstagern
email: ratnaweera@naturschutz-r-s.ch
phone: 079 220 53 21
description: > # this means to ignore newlines until "baseurl:"
  Momentan setzen wir uns ganz praktisch für die Natur ein. Wir pflegen unser Vereinsbiotop, zahlreiche Nistkästen, pflanzen nach Bedarf Hecken und wir sind politisch aktiv in der Kommission Landwirtschaft, Forst und Naturschutz.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://naturschutz-richterswil-samstagern.github.io" # the base hostname & protocol for your site
twitter_username: sinndrin
github_username: rschaerer

# Build settings
markdown: kramdown

# How to handle permalinks in the front matter
relative_permalinks: false

# Publish posts or collection documents with a future date
future: true

# Reading Files
include:
  - _pages

prose:
  metadata:
    _pages:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "published"
        field:
          element: "checkbox"
          label: "Veröffentlicht"
          value: "true"
      - name: "titleOverwrite"
        field:
          element: "text"
          label: "Titel"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
          placeholder: "z.B. /bilder/"
      - name: "headerimage"
        field:
          element: "text"
          label: "Header Bild"
          value: ""
          placeholder: "z.B. /images/header/mach-mit.jpg"
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "published"
        field:
          element: "checkbox"
          label: "Veröffentlicht"
          value: "true"
      - name: "image"
        field:
          element: "text"
          label: "Bild"
          value: ""
          placeholder: "z.B. /images/news/mini_monster.jpg"
      - name: "categories"
        field:
          element: "select"
          label: "Kategorie"
          help: "Kategorie in der dieser Beitrag erscheinen soll."
          options:
            - name: 'News'
              value: 'news'
            - name: 'Veranstaltungen'
              value: 'veranstaltungen'
      - name: "date"
        field:
          element: "text"
          label: "Datum"
          value: "CURRENT_DATETIME"
          placeholder: "z.B. 2016-08-01 15:15:38 +0200"
      - name: "veranstalungsdatumUndZeit"
        field:
          element: "text"
          label: "Veranstalungsdatum und Zeit"
          value: ""
          placeholder: "z.B. Donnerstag 6. April 2017 19:45-21:00"
      - name: "ort"
        field:
          element: "text"
          label: "Ort"
          value: ""
          placeholder: "z.B. Haus zum Bären, Dorfbachstrasse 12, Richterswil"
      - name: "tagline"
        field:
          element: "text"
          label: "Schlagzeile (Tagline)"
          value: ""
          placeholder: "Text der als Zusammenfassung auf der Übersichtseite angezeigt wird"
